const tagsEnum = {
    format: [
        '4-Koma',
        'Adaption',
        'Anthology',
        'Award Winning',
        'Doujinshi',
        'Fan Colored',
        'Full Color',
        'Long Strip',
        'Offical Colored',
        'Oneshot',
        'Self-Published',
        'Web Comic'
    ],
    genre: [
        'Action',
        'Adventure',
        'Boys Love',
        'Comedy',
        'Crime',
        'Drama',
        'Fantasy',
        'Girls Love',
        'Historical',
        'Horror',
        'Isekai',
        'Magical Girls',
        'Mecha',
        'Medical',
        'Mystery',
        'Philosophical',
        'Psychological',
        'Romance',
        'Sci-fi',
        'Slice of Life',
        'Sports',
        'Superhero',
        'Thriller',
        'Tragedy',
        'Wuxia'
    ],
    theme: [
        'Aliens',
        'Animals',
        'Cooking',
        'Crossdressing',
        'Delinquents',
        'Demons',
        'Genderswap',
        'Ghosts',
        'Gyaru',
        'Harem',
        'Incest',
        'Loli',
        'Mafia',
        'Magic',
        'Martial Arts',
        'Military',
        'Monster Girls',
        'Monsters',
        'Music',
        'Ninja',
        'Office Workers',
        'Police',
        'Post-Apocalyptic',
        'Reincarnation',
        'Reverse Harem',
        'Samurai',
        'School Life',
        'Shota',
        'Supernatural',
        'Survival',
        'Time Travel',
        'Traditional Games',
        'Vampires',
        'Video Games',
        'Villainess',
        'Virtual Reality',
        'Zombies'
    ]
}

export default tagsEnum